### ISSUE TITLE
Manual edit required of internet-of-seeds-tweet.py

### ISSUE THREAD

**Issue by alexellis** [pimoroni/internet-of-seeds#1]
Nice job with this. 

If I am reading it correctly, `internet-of-seeds-tweet.py` has to be edited manually before use. I was going to have a look at using a config file and doing a pull request if you're OK with that @sandyjmacdonald ?

Label: enhancement

Proposed changes:
- Add config.json
- Include config.example.json with dummy keys
- Add config.json to .gitignore file
- Update readme.

**Comment by sandyjmacdonald** [comment]
Go for it.

**Comment by AndiCui** [comment]
A config to disable Flotilla data logging would be great. (So flotilla is not a dependency)

**Comment by alexellis** [comment]
@AndiCui I'm looking to do this at the same time i.e. make twitter and flotilla separate classes. This would mean you could test Twitter without a live tweet going out.

**Comment by sandyjmacdonald** [comment]
There's now a config.json in which you can add your Twitter API credentials. It's in the .gitignore and there's a config.example.json. There's also sparklines for recent data trends (past 24 hours).

**Comment by alexellis** [comment]
@sandyjmacdonald I'd made these changes already and more last night as you'd given the OK for me to work on a PR.

https://github.com/alexellis/internet-of-seeds/tree/1_dependency_injection_config

These changes will also let you use a different sensor source other than flotilla when done. I'll finish it off this week and you'll have to see if it still makes sense to merge. 

Two main entrypoints:

Capture a photo and overlay sensor data on latest image.

https://github.com/alexellis/internet-of-seeds/blob/1_dependency_injection_config/capture.py

Reads last sensor log and sends media-tweet to twitter.

https://github.com/alexellis/internet-of-seeds/blob/1_dependency_injection_config/send-tweet.py
