### ISSUE TITLE
Breaking stuff up a bit [enhancement]

### ISSUE THREAD

**Issue by alexellis** [pimoroni/internet-of-seeds#3]
It'd be great to see something like this:
- send-tweet.py
- capture-photo.py
- log-sensors.py
- lib/

The cron jobs kick of the capture photo and log sensors every 5 mins etc, then the log sensors can be captured independently much more frequently without filling up the hard disk.

Inside _lib_ lives all the neat stuff for doing overlays/watermarks, capturing a photo and sending a tweet as Python classes.

What do you think?

**Comment by AndiCui** [comment]
In one emoji:👍
Go for it.

**Comment by alexellis** [comment]
@AndiCui this is for @sandyjmacdonald ... btw do you have any other suggestions?

**Comment by sandyjmacdonald** [comment]
Sounds perfect to me.

**Comment by AndiCui** [comment]
@alexellis

 #2

> What do you think?
> "You" could be plural

**Comment by alexellis** [comment]
Ping @sandyjmacdonald

**Comment by alexellis** [comment]
Did not seem to get anywhere with this, so closing.
