### ISSUE TITLE
Rename internet-of-seeds.py etc to shorter names [enhancement]

### ISSUE THREAD

**Issue by alexellis** [pimoroni/internet-of-seeds#5]
We had a quick chat about this, here's a pull request to remove the duplication in the Python names. What do you think? Good to merge to dev?

https://github.com/pimoroni/internet-of-seeds/pull/4

**Comment by sandyjmacdonald** [comment]
Yep. Happy with this.

**Comment by alexellis** [comment]
Closing - lack of activity.
